services:

  database:
    restart: always
    container_name: postgres_t1_1
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"