CREATE TABLE t_tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    due_date    DATE,
    completed   BOOLEAN      NOT NULL DEFAULT FALSE
);
